version: '2'
services:
  jenkins:
    image: 'jenkinsci/blueocean'
    container_name: accellog_jenkins
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - './data:/var/jenkins_home'
      - '/home:/home'